/** Common crypto ticker (uppercase) → CoinGecko coin `id` for `/simple/price` and `/coins/{id}`. */
export const SYMBOL_TO_CG_ID: Record<string, string> = {
  BTC: "bitcoin",
  ETH: "ethereum",
  SOL: "solana",
  ADA: "cardano",
  DOT: "polkadot",
  MATIC: "matic-network",
  POL: "matic-network",
  AVAX: "avalanche-2",
  LINK: "chainlink",
  UNI: "uniswap",
  DOGE: "dogecoin",
  SHIB: "shiba-inu",
  LTC: "litecoin",
  XRP: "ripple",
  ATOM: "cosmos",
  NEAR: "near",
  ALGO: "algorand",
  XLM: "stellar",
  VET: "vechain",
  AAVE: "aave",
  MKR: "maker",
  CRV: "curve-dao-token",
  SUSHI: "sushi",
  YFI: "yearn-finance",
  BAT: "basic-attention-token",
  ZEC: "zcash",
  XMR: "monero",
  BCH: "bitcoin-cash",
  ETC: "ethereum-classic",
  FIL: "filecoin",
  FLOW: "flow",
  ICP: "internet-computer",
  OP: "optimism",
  ARB: "arbitrum",
  TON: "the-open-network",
  APT: "aptos",
  SUI: "sui",
  TRX: "tron",
  BNB: "binancecoin",
  USDT: "tether",
  USDC: "usd-coin",
  DAI: "dai",
};

/** `symbolUpper` must already be uppercased (e.g. `BTC`). */
export function symbolToCoinGeckoId(symbolUpper: string): string {
  return SYMBOL_TO_CG_ID[symbolUpper] ?? symbolUpper.toLowerCase();
}
